SOURCES      = bzip2.c spec.c
QED_MODE     = CFCSS
NUM_CFTSS_BB = 10
APPLICATION  = bzip2
OPTIMIZATION = 
BENCHLANG    = C

# Include standard template for this suite
-include ../Makefile.defaults

nomakefiles:
	@echo "*** Oops!  I didn't find a Makefile.defaults file. "
	@echo