SOURCES      = Parax.cpp
QED_MODE     = ALL
NUM_CFTSS_BB = 10
APPLICATION  = Parax
OPTIMIZATION = 
BENCHLANG    = C++

# Include standard template for this suite
-include ../Makefile.defaults

nomakefiles:
	@echo "*** Oops!  I didn't find a Makefile.defaults file. "
	@echo