# Commonalities between the two testing subdirectories.

OPT = -O2 # feel free to play with this
CC = clang
CFLAGS = $(OPT) -Wall

LLC = llc
LLC_FLAGS = -disable-cfi -disable-verify $(OPT)

clean:
	rm -f *.ll *.bc *.native *.s
