//This program generated by a Python script.
#include <stdio.h>
#define lprintf for(int i = 0; i < level; i++) printf("  "); printf

int level = 0;


int i0();
int i1();
int i2();
int i3();
int i4();
int i5();
int i6();
int i7();
int i8();
int i9();
int i10();
int i11();
int i12();
int i13();
int i14();
int i15();
int i16();
int i17();
int i18();
int i19();
int i20();
int i21();
int i22();
int i23();
int i24();
int i25();
int i26();
int i27();
int i28();
int i29();
int i30();
int i31();
int i32();
int i33();
int i34();
int i35();
int i36();
int i37();
int i38();
int i39();
int i40();
int i41();
int i42();
int i43();
int i44();
int i45();
int i46();
int i47();
int i48();
int i49();
int i50();
int i51();
int i52();
int i53();
int i54();
int i55();
int i56();
int i57();
int i58();
int i59();
int i60();
int i61();
int i62();
int i63();
int i64();
int i65();
int i66();
int i67();
int i68();
int i69();
int i70();
int i71();
int i72();
int i73();
int i74();
int i75();
int i76();
int i77();
int i78();
int i79();
int i80();
int i81();
int i82();
int i83();
int i84();
int i85();
int i86();
int i87();
int i88();
int i89();
int i90();
int i91();
int i92();
int i93();
int i94();
int i95();
int i96();

int i0() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi0\033[0m.\n");
	if (!called) {
		i3();
		i65();
		i80();
		i77();
		i49();
		i14();
		i84();
		i0();
		i18();
	}
	level--;
	return 0;
}

int i1() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi1\033[0m.\n");
	if (!called) {
		i13();
		i74();
		i39();
		i36();
		i82();
		i25();
		i41();
		i53();
		i29();
		i37();
		i47();
		i73();
		i17();
		i32();
		i92();
		i70();
		i94();
		i68();
		i67();
		i4();
		i5();
	}
	level--;
	return 0;
}

int i2() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi2\033[0m.\n");
	if (!called) {
		i82();
		i17();
		i74();
		i64();
		i33();
		i50();
		i51();
		i20();
		i93();
		i29();
		i47();
		i14();
		i71();
		i52();
		i36();
		i17();
		i65();
		i0();
		i41();
	}
	level--;
	return 0;
}

int i3() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi3\033[0m.\n");
	if (!called) {
		i11();
		i72();
		i31();
		i61();
		i16();
		i53();
		i72();
		i16();
		i88();
		i75();
		i71();
		i32();
		i53();
		i94();
		i92();
		i11();
		i8();
		i76();
		i25();
		i58();
		i16();
		i61();
		i28();
		i38();
	}
	level--;
	return 0;
}

int i4() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi4\033[0m.\n");
	if (!called) {
		i62();
		i55();
		i55();
		i75();
		i17();
		i42();
		i43();
		i58();
		i19();
		i27();
		i57();
		i19();
		i41();
		i82();
		i92();
		i48();
		i38();
		i0();
		i85();
		i67();
		i32();
		i64();
		i95();
	}
	level--;
	return 0;
}

int i5() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi5\033[0m.\n");
	if (!called) {
		i5();
		i16();
		i53();
		i36();
		i52();
		i32();
		i78();
		i4();
		i69();
		i32();
		i96();
		i88();
		i44();
		i27();
		i42();
		i14();
		i1();
		i87();
		i19();
		i10();
		i40();
		i91();
		i75();
		i10();
		i44();
	}
	level--;
	return 0;
}

int i6() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi6\033[0m.\n");
	if (!called) {
		i66();
		i75();
		i29();
		i40();
		i85();
		i45();
		i18();
		i36();
		i4();
		i8();
		i76();
		i15();
		i75();
		i40();
		i84();
		i84();
		i66();
		i85();
		i3();
		i49();
	}
	level--;
	return 0;
}

int i7() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi7\033[0m.\n");
	if (!called) {
		i21();
		i63();
		i54();
	}
	level--;
	return 0;
}

int i8() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi8\033[0m.\n");
	if (!called) {
		i63();
		i3();
		i80();
		i84();
		i57();
	}
	level--;
	return 0;
}

int i9() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi9\033[0m.\n");
	if (!called) {
		i46();
		i12();
		i83();
		i47();
		i19();
		i41();
		i71();
		i34();
		i5();
		i4();
		i37();
		i27();
		i27();
	}
	level--;
	return 0;
}

int i10() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi10\033[0m.\n");
	if (!called) {
		i45();
		i46();
		i74();
		i73();
		i16();
		i72();
		i84();
		i55();
		i82();
		i33();
		i96();
		i38();
		i46();
		i46();
		i62();
		i57();
		i83();
		i88();
		i51();
		i21();
	}
	level--;
	return 0;
}

int i11() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi11\033[0m.\n");
	if (!called) {
		i95();
		i77();
		i14();
		i86();
		i12();
		i78();
		i26();
		i81();
		i57();
		i41();
	}
	level--;
	return 0;
}

int i12() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi12\033[0m.\n");
	if (!called) {
		i0();
		i21();
		i32();
		i0();
		i39();
	}
	level--;
	return 0;
}

int i13() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi13\033[0m.\n");
	if (!called) {
		i55();
		i60();
		i45();
	}
	level--;
	return 0;
}

int i14() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi14\033[0m.\n");
	if (!called) {
		i1();
		i88();
		i96();
		i95();
		i78();
		i89();
		i15();
		i62();
		i50();
		i46();
		i39();
		i38();
		i67();
		i73();
		i69();
		i12();
		i41();
		i38();
		i50();
		i54();
		i94();
		i85();
		i14();
		i54();
	}
	level--;
	return 0;
}

int i15() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi15\033[0m.\n");
	if (!called) {
		i81();
		i23();
		i55();
		i5();
		i81();
		i60();
		i36();
		i20();
		i32();
		i10();
		i1();
	}
	level--;
	return 0;
}

int i16() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi16\033[0m.\n");
	if (!called) {
		i12();
	}
	level--;
	return 0;
}

int i17() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi17\033[0m.\n");
	if (!called) {
		i0();
		i44();
		i42();
		i18();
		i71();
		i77();
		i34();
		i81();
		i79();
		i64();
		i71();
		i86();
		i8();
		i37();
		i16();
		i30();
		i91();
	}
	level--;
	return 0;
}

int i18() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi18\033[0m.\n");
	if (!called) {
		i70();
		i35();
		i36();
		i77();
		i70();
		i91();
		i71();
		i14();
		i31();
		i85();
		i79();
		i74();
		i41();
		i1();
		i91();
		i68();
		i0();
		i93();
		i33();
	}
	level--;
	return 0;
}

int i19() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi19\033[0m.\n");
	if (!called) {
		i17();
		i37();
		i55();
		i5();
		i13();
		i12();
		i39();
		i78();
		i63();
		i26();
		i2();
		i53();
		i57();
		i11();
		i58();
		i2();
		i43();
		i39();
		i59();
		i24();
		i45();
		i82();
		i91();
		i88();
		i81();
	}
	level--;
	return 0;
}

int i20() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi20\033[0m.\n");
	if (!called) {
		i94();
		i91();
		i57();
		i84();
		i18();
		i6();
		i55();
		i40();
		i58();
		i66();
		i83();
		i76();
	}
	level--;
	return 0;
}

int i21() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi21\033[0m.\n");
	if (!called) {
		i46();
		i72();
		i1();
		i25();
		i45();
		i29();
		i86();
		i23();
		i0();
		i94();
		i63();
		i0();
		i61();
		i63();
		i59();
		i94();
		i44();
		i17();
		i67();
		i89();
		i89();
		i72();
		i70();
		i35();
		i35();
		i8();
		i78();
		i7();
		i22();
	}
	level--;
	return 0;
}

int i22() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi22\033[0m.\n");
	if (!called) {
		i25();
		i77();
		i16();
		i43();
		i23();
		i2();
		i52();
		i29();
		i56();
		i23();
		i36();
		i27();
		i69();
		i90();
		i74();
		i15();
	}
	level--;
	return 0;
}

int i23() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi23\033[0m.\n");
	if (!called) {
		i69();
		i85();
		i23();
		i52();
		i43();
		i29();
		i5();
		i72();
		i84();
		i82();
		i54();
		i26();
		i72();
		i55();
		i6();
		i35();
		i15();
		i8();
		i50();
		i34();
		i40();
		i34();
	}
	level--;
	return 0;
}

int i24() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi24\033[0m.\n");
	if (!called) {
		i21();
		i83();
		i47();
		i90();
		i61();
		i27();
		i28();
		i22();
		i11();
		i81();
		i12();
		i0();
		i5();
		i37();
		i94();
		i49();
		i70();
		i87();
		i39();
		i44();
		i41();
		i57();
		i15();
		i9();
		i4();
		i74();
	}
	level--;
	return 0;
}

int i25() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi25\033[0m.\n");
	if (!called) {
		i88();
		i5();
		i15();
		i45();
		i70();
		i88();
		i70();
	}
	level--;
	return 0;
}

int i26() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi26\033[0m.\n");
	if (!called) {
		i88();
		i88();
		i83();
		i23();
		i34();
		i8();
		i30();
		i25();
		i30();
		i77();
		i80();
		i44();
		i95();
		i89();
		i94();
		i54();
		i39();
		i29();
		i63();
		i17();
		i25();
		i55();
		i90();
		i88();
		i34();
		i61();
		i46();
		i21();
	}
	level--;
	return 0;
}

int i27() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi27\033[0m.\n");
	if (!called) {
		i89();
		i69();
		i23();
		i6();
		i58();
		i96();
		i73();
		i25();
		i24();
		i45();
		i33();
		i78();
		i49();
		i39();
		i48();
		i48();
		i64();
		i27();
		i90();
		i30();
		i64();
		i30();
	}
	level--;
	return 0;
}

int i28() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi28\033[0m.\n");
	if (!called) {
		i37();
		i86();
		i53();
		i38();
		i24();
	}
	level--;
	return 0;
}

int i29() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi29\033[0m.\n");
	if (!called) {
		i47();
	}
	level--;
	return 0;
}

int i30() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi30\033[0m.\n");
	if (!called) {
		i25();
		i88();
		i96();
		i31();
		i73();
		i15();
		i68();
		i88();
		i87();
		i71();
		i85();
		i21();
		i6();
		i55();
		i93();
		i95();
		i75();
		i80();
		i63();
		i57();
		i1();
		i70();
		i65();
		i62();
		i35();
		i31();
		i50();
		i58();
		i59();
	}
	level--;
	return 0;
}

int i31() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi31\033[0m.\n");
	if (!called) {
		i18();
		i92();
		i60();
		i59();
		i88();
		i81();
		i20();
		i28();
		i95();
		i48();
		i93();
		i93();
		i18();
		i28();
		i77();
		i68();
		i39();
		i4();
	}
	level--;
	return 0;
}

int i32() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi32\033[0m.\n");
	if (!called) {
		i34();
		i33();
		i42();
		i0();
		i43();
		i46();
		i69();
		i96();
		i39();
		i23();
		i0();
	}
	level--;
	return 0;
}

int i33() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi33\033[0m.\n");
	if (!called) {
		i36();
		i4();
		i4();
		i46();
		i44();
		i14();
		i48();
		i91();
		i88();
		i91();
		i15();
		i54();
		i86();
		i2();
		i77();
		i31();
		i40();
		i67();
		i28();
		i74();
		i16();
		i92();
		i91();
		i77();
		i82();
	}
	level--;
	return 0;
}

int i34() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi34\033[0m.\n");
	if (!called) {
		i30();
		i75();
		i34();
		i41();
		i59();
		i13();
		i54();
		i34();
		i70();
		i75();
		i23();
		i32();
		i39();
		i85();
		i51();
		i55();
		i92();
		i93();
		i30();
		i75();
	}
	level--;
	return 0;
}

int i35() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi35\033[0m.\n");
	if (!called) {
		i53();
		i76();
		i62();
		i52();
		i68();
		i39();
		i16();
		i59();
		i2();
		i62();
		i57();
		i91();
		i70();
		i29();
		i94();
		i86();
		i83();
	}
	level--;
	return 0;
}

int i36() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi36\033[0m.\n");
	if (!called) {
		i24();
		i15();
		i52();
		i79();
		i38();
		i33();
		i81();
		i73();
		i26();
		i81();
		i63();
		i14();
		i43();
		i96();
		i68();
		i92();
		i60();
		i90();
		i45();
		i79();
		i49();
		i26();
		i90();
		i80();
		i78();
		i8();
		i10();
	}
	level--;
	return 0;
}

int i37() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi37\033[0m.\n");
	if (!called) {
		i75();
		i58();
		i40();
		i38();
		i6();
		i74();
		i90();
		i18();
		i26();
		i72();
		i61();
		i15();
		i8();
	}
	level--;
	return 0;
}

int i38() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi38\033[0m.\n");
	if (!called) {
		i68();
		i13();
		i60();
		i93();
		i58();
		i22();
		i5();
		i85();
		i52();
		i55();
		i21();
		i88();
		i14();
		i25();
		i45();
		i55();
		i55();
		i47();
		i51();
		i3();
		i6();
		i67();
		i76();
	}
	level--;
	return 0;
}

int i39() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi39\033[0m.\n");
	if (!called) {
		i58();
		i70();
		i88();
		i29();
		i44();
		i48();
		i79();
	}
	level--;
	return 0;
}

int i40() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi40\033[0m.\n");
	if (!called) {
		i93();
		i42();
		i0();
		i92();
	}
	level--;
	return 0;
}

int i41() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi41\033[0m.\n");
	if (!called) {
		i14();
		i12();
		i77();
		i93();
		i68();
		i7();
		i15();
		i33();
		i28();
		i54();
		i63();
		i71();
		i94();
		i7();
		i30();
		i43();
		i90();
		i9();
		i52();
		i93();
		i19();
		i3();
		i22();
		i30();
		i1();
		i89();
		i24();
		i4();
		i29();
	}
	level--;
	return 0;
}

int i42() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi42\033[0m.\n");
	if (!called) {
		i63();
		i60();
		i41();
		i36();
		i54();
		i69();
		i43();
		i26();
		i34();
		i96();
		i85();
		i27();
		i46();
		i46();
		i30();
		i30();
		i7();
		i14();
		i13();
		i70();
		i63();
		i79();
	}
	level--;
	return 0;
}

int i43() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi43\033[0m.\n");
	if (!called) {
		i1();
		i78();
		i80();
		i94();
		i41();
		i74();
		i40();
		i26();
		i19();
	}
	level--;
	return 0;
}

int i44() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi44\033[0m.\n");
	if (!called) {
		i86();
		i41();
		i47();
		i94();
	}
	level--;
	return 0;
}

int i45() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi45\033[0m.\n");
	if (!called) {
		i23();
		i76();
	}
	level--;
	return 0;
}

int i46() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi46\033[0m.\n");
	if (!called) {
		i17();
	}
	level--;
	return 0;
}

int i47() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi47\033[0m.\n");
	if (!called) {
		i93();
		i72();
		i71();
		i4();
		i51();
		i17();
		i77();
		i94();
		i96();
		i14();
		i36();
		i60();
		i65();
		i41();
		i82();
		i86();
		i63();
		i56();
		i1();
		i7();
		i42();
		i63();
		i28();
	}
	level--;
	return 0;
}

int i48() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi48\033[0m.\n");
	if (!called) {
		i70();
		i37();
		i18();
		i39();
		i63();
		i22();
		i2();
		i49();
		i23();
		i57();
		i45();
		i1();
		i21();
		i40();
		i77();
		i46();
		i13();
		i83();
		i42();
		i66();
		i88();
		i0();
		i39();
		i60();
	}
	level--;
	return 0;
}

int i49() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi49\033[0m.\n");
	if (!called) {
		i49();
		i22();
		i74();
		i90();
		i91();
		i73();
		i79();
		i36();
		i8();
		i59();
		i17();
		i96();
		i78();
		i95();
		i78();
		i2();
		i66();
		i38();
		i15();
		i67();
		i63();
		i0();
		i93();
		i26();
		i45();
		i0();
	}
	level--;
	return 0;
}

int i50() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi50\033[0m.\n");
	if (!called) {
		i33();
		i86();
		i20();
		i67();
		i46();
		i40();
	}
	level--;
	return 0;
}

int i51() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi51\033[0m.\n");
	if (!called) {
		i91();
		i17();
		i66();
		i90();
		i71();
		i24();
		i6();
		i36();
		i78();
		i89();
		i83();
		i0();
		i24();
		i57();
		i32();
		i89();
		i48();
		i86();
		i5();
		i84();
		i75();
		i69();
		i23();
		i55();
		i58();
		i46();
		i2();
		i92();
		i78();
	}
	level--;
	return 0;
}

int i52() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi52\033[0m.\n");
	if (!called) {
		i62();
		i7();
		i9();
		i68();
		i73();
		i96();
		i39();
		i30();
		i28();
		i75();
		i34();
		i78();
		i36();
		i5();
		i1();
		i38();
		i84();
		i86();
		i23();
		i34();
		i76();
	}
	level--;
	return 0;
}

int i53() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi53\033[0m.\n");
	if (!called) {
		i96();
		i7();
		i54();
		i73();
		i71();
		i88();
		i28();
		i64();
		i64();
		i96();
		i80();
		i6();
		i33();
		i90();
		i16();
		i41();
		i46();
		i72();
		i34();
		i74();
		i81();
		i79();
	}
	level--;
	return 0;
}

int i54() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi54\033[0m.\n");
	if (!called) {
		i4();
		i62();
		i50();
		i54();
		i81();
		i27();
		i74();
		i37();
		i29();
		i49();
		i45();
		i36();
		i70();
		i17();
		i80();
	}
	level--;
	return 0;
}

int i55() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi55\033[0m.\n");
	if (!called) {
		i2();
		i66();
		i86();
		i90();
		i69();
		i64();
		i34();
		i87();
		i53();
		i94();
		i18();
		i55();
		i23();
		i94();
		i30();
		i57();
		i72();
		i83();
		i29();
		i26();
		i50();
		i89();
		i65();
		i25();
		i38();
		i89();
		i84();
	}
	level--;
	return 0;
}

int i56() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi56\033[0m.\n");
	if (!called) {
		i65();
		i78();
		i0();
		i13();
	}
	level--;
	return 0;
}

int i57() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi57\033[0m.\n");
	if (!called) {
		i16();
		i67();
		i55();
		i0();
		i81();
		i59();
		i67();
		i7();
		i65();
		i95();
		i12();
		i95();
		i42();
		i28();
		i29();
		i82();
		i24();
	}
	level--;
	return 0;
}

int i58() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi58\033[0m.\n");
	if (!called) {
		i42();
		i80();
		i28();
		i86();
		i35();
		i81();
		i37();
		i48();
		i15();
		i91();
		i69();
		i71();
		i10();
		i23();
		i26();
		i43();
		i3();
		i35();
		i5();
		i84();
	}
	level--;
	return 0;
}

int i59() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi59\033[0m.\n");
	if (!called) {
		i18();
		i53();
		i83();
		i69();
		i38();
		i83();
		i87();
		i27();
		i0();
		i93();
		i22();
		i70();
		i48();
		i40();
		i25();
		i50();
		i42();
		i67();
		i16();
	}
	level--;
	return 0;
}

int i60() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi60\033[0m.\n");
	if (!called) {
		i3();
		i32();
		i69();
		i45();
		i17();
		i50();
		i19();
		i72();
		i86();
		i21();
		i37();
		i84();
		i7();
		i77();
		i72();
	}
	level--;
	return 0;
}

int i61() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi61\033[0m.\n");
	if (!called) {
		i75();
		i76();
	}
	level--;
	return 0;
}

int i62() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi62\033[0m.\n");
	if (!called) {
		i70();
		i67();
		i62();
		i18();
		i81();
		i33();
		i91();
		i48();
		i94();
		i76();
		i76();
		i9();
		i2();
		i64();
		i41();
		i88();
		i73();
		i8();
		i42();
		i79();
		i35();
		i0();
	}
	level--;
	return 0;
}

int i63() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi63\033[0m.\n");
	if (!called) {
		i7();
		i4();
		i16();
	}
	level--;
	return 0;
}

int i64() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi64\033[0m.\n");
	if (!called) {
		i45();
		i61();
		i41();
		i87();
		i86();
		i70();
		i0();
		i43();
		i13();
		i26();
		i62();
		i13();
		i43();
		i41();
		i19();
		i82();
	}
	level--;
	return 0;
}

int i65() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi65\033[0m.\n");
	if (!called) {
		i63();
		i27();
		i68();
		i94();
		i91();
		i91();
		i31();
		i60();
		i21();
		i61();
		i58();
		i87();
		i0();
		i37();
		i31();
		i21();
		i27();
		i62();
		i10();
		i47();
		i90();
		i9();
		i23();
		i71();
		i18();
	}
	level--;
	return 0;
}

int i66() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi66\033[0m.\n");
	if (!called) {
		i55();
		i75();
		i37();
		i75();
		i34();
		i21();
		i52();
		i70();
		i7();
		i41();
		i8();
		i62();
		i82();
		i81();
		i11();
		i17();
		i27();
		i16();
		i82();
		i15();
		i18();
		i34();
		i44();
		i78();
	}
	level--;
	return 0;
}

int i67() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi67\033[0m.\n");
	if (!called) {
		i83();
		i68();
		i64();
		i41();
		i57();
		i60();
		i40();
	}
	level--;
	return 0;
}

int i68() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi68\033[0m.\n");
	if (!called) {
		i46();
		i32();
		i85();
		i29();
		i85();
		i26();
		i68();
		i91();
		i59();
		i84();
		i42();
	}
	level--;
	return 0;
}

int i69() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi69\033[0m.\n");
	if (!called) {
		i21();
		i1();
		i61();
		i56();
		i25();
		i95();
		i68();
		i45();
		i33();
		i20();
		i84();
		i85();
		i27();
	}
	level--;
	return 0;
}

int i70() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi70\033[0m.\n");
	if (!called) {
		i67();
		i5();
		i82();
		i12();
		i21();
		i77();
		i95();
		i83();
		i83();
		i15();
		i81();
		i43();
		i84();
		i76();
	}
	level--;
	return 0;
}

int i71() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi71\033[0m.\n");
	if (!called) {
		i15();
		i33();
		i53();
		i4();
		i41();
		i27();
		i42();
		i6();
		i83();
		i21();
		i18();
		i64();
		i51();
		i89();
		i59();
		i41();
		i79();
	}
	level--;
	return 0;
}

int i72() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi72\033[0m.\n");
	if (!called) {
		i44();
		i4();
		i93();
		i64();
		i41();
		i30();
		i20();
		i76();
		i68();
		i26();
		i7();
		i31();
		i25();
		i85();
		i60();
		i42();
		i93();
		i33();
		i27();
		i65();
	}
	level--;
	return 0;
}

int i73() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi73\033[0m.\n");
	if (!called) {
		i79();
		i35();
		i29();
	}
	level--;
	return 0;
}

int i74() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi74\033[0m.\n");
	if (!called) {
		i26();
		i51();
		i27();
		i27();
		i49();
		i12();
		i15();
		i57();
		i80();
		i68();
		i84();
		i2();
		i43();
		i69();
		i77();
	}
	level--;
	return 0;
}

int i75() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi75\033[0m.\n");
	if (!called) {
		i39();
		i60();
		i38();
		i12();
		i36();
		i94();
		i79();
		i96();
		i79();
		i38();
		i41();
		i16();
		i86();
		i23();
		i13();
		i76();
		i0();
		i45();
	}
	level--;
	return 0;
}

int i76() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi76\033[0m.\n");
	if (!called) {
		i82();
		i27();
		i59();
		i12();
		i32();
		i73();
		i56();
		i22();
		i13();
		i23();
		i59();
		i12();
		i59();
		i26();
		i94();
		i54();
		i92();
		i72();
		i93();
		i15();
		i74();
		i56();
		i96();
		i84();
		i35();
		i4();
	}
	level--;
	return 0;
}

int i77() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi77\033[0m.\n");
	if (!called) {
		i8();
		i64();
		i37();
		i70();
		i54();
		i69();
		i2();
		i58();
		i5();
		i5();
		i7();
		i38();
		i33();
		i86();
		i66();
		i3();
		i76();
	}
	level--;
	return 0;
}

int i78() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi78\033[0m.\n");
	if (!called) {
		i38();
		i29();
		i40();
	}
	level--;
	return 0;
}

int i79() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi79\033[0m.\n");
	if (!called) {
		i29();
		i57();
		i82();
		i13();
		i92();
		i86();
		i78();
		i35();
		i8();
		i9();
		i87();
		i43();
		i76();
		i93();
		i74();
		i32();
		i87();
	}
	level--;
	return 0;
}

int i80() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi80\033[0m.\n");
	if (!called) {
		i69();
		i26();
	}
	level--;
	return 0;
}

int i81() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi81\033[0m.\n");
	if (!called) {
		i76();
		i73();
		i44();
	}
	level--;
	return 0;
}

int i82() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi82\033[0m.\n");
	if (!called) {
		i9();
		i47();
		i16();
		i4();
		i50();
		i55();
		i57();
		i66();
		i35();
		i30();
		i9();
		i12();
		i41();
		i60();
		i88();
		i19();
		i59();
		i42();
		i71();
		i81();
	}
	level--;
	return 0;
}

int i83() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi83\033[0m.\n");
	if (!called) {
		i26();
	}
	level--;
	return 0;
}

int i84() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi84\033[0m.\n");
	if (!called) {
		i45();
		i9();
		i90();
		i14();
		i27();
		i39();
		i17();
		i58();
		i44();
		i38();
		i30();
		i4();
		i71();
		i50();
		i37();
		i18();
		i31();
		i29();
		i14();
		i27();
		i95();
		i20();
		i37();
	}
	level--;
	return 0;
}

int i85() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi85\033[0m.\n");
	if (!called) {
		i10();
		i23();
		i63();
		i80();
		i71();
	}
	level--;
	return 0;
}

int i86() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi86\033[0m.\n");
	if (!called) {
		i36();
		i34();
		i91();
		i51();
		i61();
		i23();
		i6();
		i24();
		i0();
		i9();
		i4();
	}
	level--;
	return 0;
}

int i87() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi87\033[0m.\n");
	if (!called) {
		i11();
		i61();
		i17();
		i55();
		i34();
		i26();
		i39();
		i84();
		i62();
		i0();
		i52();
		i15();
		i44();
		i87();
		i20();
	}
	level--;
	return 0;
}

int i88() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi88\033[0m.\n");
	if (!called) {
		i59();
		i14();
		i9();
		i63();
		i4();
		i28();
		i19();
		i51();
		i47();
		i47();
		i21();
		i95();
		i20();
		i70();
		i3();
		i46();
		i65();
	}
	level--;
	return 0;
}

int i89() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi89\033[0m.\n");
	if (!called) {
		i26();
		i53();
		i56();
		i22();
		i20();
		i57();
		i20();
		i66();
		i32();
		i79();
		i8();
		i74();
	}
	level--;
	return 0;
}

int i90() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi90\033[0m.\n");
	if (!called) {
		i62();
		i14();
		i64();
		i73();
		i96();
		i11();
		i84();
		i46();
		i16();
		i33();
		i87();
		i25();
		i17();
		i6();
		i20();
		i67();
		i66();
	}
	level--;
	return 0;
}

int i91() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi91\033[0m.\n");
	if (!called) {
		i67();
		i0();
		i45();
		i86();
		i1();
		i80();
	}
	level--;
	return 0;
}

int i92() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi92\033[0m.\n");
	if (!called) {
		i9();
		i42();
		i31();
		i5();
		i41();
		i85();
		i78();
		i37();
		i48();
		i0();
		i18();
		i95();
		i71();
		i95();
		i55();
		i47();
		i6();
		i28();
		i10();
		i89();
		i78();
		i4();
		i19();
		i89();
		i92();
	}
	level--;
	return 0;
}

int i93() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi93\033[0m.\n");
	if (!called) {
		i92();
		i22();
		i68();
		i96();
		i9();
		i91();
		i75();
		i82();
		i8();
		i91();
		i85();
		i80();
		i71();
		i30();
	}
	level--;
	return 0;
}

int i94() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi94\033[0m.\n");
	if (!called) {
		i76();
		i56();
		i93();
		i43();
		i31();
		i25();
		i45();
		i49();
		i43();
		i28();
		i92();
		i73();
		i48();
		i27();
		i93();
		i71();
		i14();
		i42();
		i8();
		i41();
		i11();
		i23();
		i63();
		i72();
		i78();
		i75();
	}
	level--;
	return 0;
}

int i95() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi95\033[0m.\n");
	if (!called) {
		i83();
		i28();
		i90();
		i20();
		i54();
		i14();
		i82();
		i56();
		i34();
		i64();
		i40();
		i66();
		i63();
		i9();
		i57();
		i76();
		i51();
		i13();
		i46();
		i10();
	}
	level--;
	return 0;
}

int i96() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi96\033[0m.\n");
	if (!called) {
		i85();
		i16();
		i46();
		i51();
		i23();
		i80();
		i45();
		i41();
		i71();
		i61();
		i40();
		i56();
		i13();
		i22();
		i92();
	}
	level--;
	return 0;
}

int main() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mmain\033[0m.\n");
	if (!called) {
		i92();
		i67();
		i84();
		i7();
		i81();
		i82();
		i73();
		i4();
		i90();
		i52();
		i27();
		i22();
		i25();
		i16();
		i21();
		i4();
		i14();
		i46();
		i67();
		i46();
		i47();
		i52();
		i59();
		i45();
	}
	level--;
	return 0;
}

