//This program generated by a Python script.
#include <stdio.h>
#define lprintf for(int i = 0; i < level; i++) printf("  "); printf

int level = 0;


int i0();
int i1();
int i2();
int i3();
int i4();
int i5();
int i6();
int i7();
int i8();
int i9();
int i10();
int i11();
int i12();
int i13();
int i14();
int i15();
int i16();
int i17();
int i18();
int i19();
int i20();
int i21();
int i22();
int i23();
int i24();
int i25();
int i26();
int i27();
int i28();
int i29();
int i30();

int i0() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi0\033[0m.\n");
	if (!called) {
		i25();
		i1();
		i11();
		i30();
		i12();
		i16();
		i3();
		i2();
		i2();
		i21();
		i11();
		i9();
		i0();
		i16();
		i17();
		i24();
		i4();
		i5();
		i29();
		i20();
		i0();
		i3();
		i11();
	}
	level--;
	return 0;
}

int i1() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi1\033[0m.\n");
	if (!called) {
		i30();
		i18();
		i6();
		i26();
		i23();
		i8();
		i11();
		i19();
		i19();
		i25();
		i24();
		i2();
		i21();
		i14();
		i26();
		i24();
		i7();
		i24();
		i4();
		i7();
	}
	level--;
	return 0;
}

int i2() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi2\033[0m.\n");
	if (!called) {
		i29();
		i24();
		i5();
		i0();
		i24();
		i10();
		i2();
		i8();
		i12();
		i19();
		i19();
		i6();
		i14();
		i6();
		i0();
		i8();
		i30();
		i3();
		i9();
		i12();
		i9();
		i20();
		i27();
		i12();
		i6();
	}
	level--;
	return 0;
}

int i3() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi3\033[0m.\n");
	if (!called) {
		i19();
		i19();
		i28();
		i1();
		i7();
		i19();
		i12();
		i14();
		i12();
		i28();
		i16();
		i29();
		i22();
		i6();
		i25();
		i24();
	}
	level--;
	return 0;
}

int i4() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi4\033[0m.\n");
	if (!called) {
		i25();
		i3();
		i24();
		i0();
		i28();
		i9();
		i11();
		i25();
		i15();
		i0();
		i13();
		i29();
		i1();
		i12();
		i12();
		i13();
		i27();
		i29();
	}
	level--;
	return 0;
}

int i5() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi5\033[0m.\n");
	if (!called) {
		i19();
		i13();
		i10();
		i13();
		i20();
		i23();
		i12();
		i2();
		i1();
		i18();
		i18();
		i28();
		i5();
		i6();
		i18();
		i21();
		i22();
		i18();
		i14();
		i2();
		i6();
		i24();
	}
	level--;
	return 0;
}

int i6() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi6\033[0m.\n");
	if (!called) {
		i22();
		i2();
		i15();
		i19();
		i15();
		i13();
		i19();
		i13();
		i0();
		i23();
		i17();
		i30();
		i22();
		i2();
		i26();
		i29();
		i30();
		i28();
		i28();
		i2();
	}
	level--;
	return 0;
}

int i7() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi7\033[0m.\n");
	if (!called) {
		i17();
		i7();
		i17();
		i1();
		i17();
		i17();
		i7();
		i3();
		i22();
		i12();
		i21();
		i27();
		i5();
		i21();
		i13();
		i5();
		i22();
		i12();
		i1();
		i17();
		i13();
		i8();
	}
	level--;
	return 0;
}

int i8() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi8\033[0m.\n");
	if (!called) {
		i21();
		i16();
		i14();
		i7();
		i20();
		i1();
		i10();
		i7();
		i28();
		i20();
		i1();
		i10();
		i8();
		i14();
		i20();
		i27();
		i16();
		i2();
		i2();
		i23();
		i6();
		i19();
		i30();
		i23();
		i4();
		i5();
		i14();
		i5();
		i25();
	}
	level--;
	return 0;
}

int i9() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi9\033[0m.\n");
	if (!called) {
		i12();
		i28();
		i24();
		i7();
		i9();
		i16();
		i14();
		i1();
		i30();
		i19();
		i1();
		i22();
		i21();
		i3();
		i14();
		i29();
		i9();
		i1();
		i18();
		i22();
	}
	level--;
	return 0;
}

int i10() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi10\033[0m.\n");
	if (!called) {
		i26();
		i19();
		i25();
		i24();
		i8();
		i17();
		i3();
		i4();
		i7();
		i9();
		i22();
		i5();
		i0();
		i1();
		i15();
		i7();
		i10();
	}
	level--;
	return 0;
}

int i11() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi11\033[0m.\n");
	if (!called) {
		i14();
		i0();
		i17();
		i13();
		i21();
		i3();
		i26();
		i6();
		i7();
		i0();
		i20();
		i0();
		i27();
		i13();
		i18();
		i26();
		i4();
		i17();
		i1();
		i8();
		i15();
		i21();
		i10();
		i26();
		i20();
		i7();
		i17();
		i10();
		i15();
	}
	level--;
	return 0;
}

int i12() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi12\033[0m.\n");
	if (!called) {
		i27();
		i13();
		i17();
		i3();
		i23();
		i14();
		i16();
		i11();
		i23();
		i5();
		i0();
		i17();
		i14();
		i30();
		i19();
		i27();
		i3();
		i4();
		i22();
		i10();
		i7();
		i7();
		i8();
		i15();
		i1();
		i24();
		i0();
		i5();
		i1();
	}
	level--;
	return 0;
}

int i13() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi13\033[0m.\n");
	if (!called) {
		i27();
		i5();
		i20();
		i18();
		i14();
		i8();
		i21();
		i8();
		i10();
		i17();
		i20();
		i9();
		i23();
		i30();
		i1();
		i3();
		i14();
		i19();
		i21();
		i3();
		i27();
		i8();
		i8();
		i21();
		i8();
		i18();
		i14();
	}
	level--;
	return 0;
}

int i14() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi14\033[0m.\n");
	if (!called) {
		i15();
		i5();
		i21();
		i14();
		i17();
		i24();
		i4();
		i7();
		i2();
		i8();
		i21();
		i5();
		i24();
		i1();
		i9();
		i3();
		i1();
		i26();
		i19();
		i16();
	}
	level--;
	return 0;
}

int i15() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi15\033[0m.\n");
	if (!called) {
		i23();
		i14();
		i23();
		i22();
		i2();
		i19();
		i13();
		i30();
		i1();
		i11();
		i0();
		i19();
		i25();
		i13();
		i10();
		i3();
		i22();
		i25();
		i9();
		i18();
	}
	level--;
	return 0;
}

int i16() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi16\033[0m.\n");
	if (!called) {
		i9();
		i2();
		i5();
		i0();
		i26();
		i9();
		i17();
		i3();
		i27();
		i22();
		i13();
		i26();
		i5();
		i6();
		i27();
		i19();
		i21();
		i25();
		i4();
		i13();
		i30();
		i30();
		i0();
		i3();
		i12();
	}
	level--;
	return 0;
}

int i17() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi17\033[0m.\n");
	if (!called) {
		i18();
		i14();
		i29();
		i16();
		i23();
		i7();
		i6();
		i5();
		i0();
		i29();
		i27();
		i16();
		i30();
		i18();
		i27();
		i0();
		i22();
		i2();
		i25();
		i27();
		i19();
		i10();
		i16();
		i22();
		i27();
		i19();
		i0();
	}
	level--;
	return 0;
}

int i18() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi18\033[0m.\n");
	if (!called) {
		i25();
		i19();
		i6();
		i1();
		i8();
		i15();
		i16();
		i23();
		i26();
		i4();
		i2();
		i13();
		i5();
		i29();
		i27();
		i14();
		i5();
	}
	level--;
	return 0;
}

int i19() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi19\033[0m.\n");
	if (!called) {
		i5();
		i21();
		i16();
		i9();
		i23();
		i17();
		i6();
		i27();
		i4();
		i27();
		i20();
		i26();
		i13();
		i5();
		i9();
		i18();
		i5();
		i18();
		i27();
		i16();
		i27();
		i27();
		i8();
	}
	level--;
	return 0;
}

int i20() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi20\033[0m.\n");
	if (!called) {
		i14();
		i7();
		i29();
		i25();
		i9();
		i25();
		i25();
		i10();
		i5();
		i15();
		i4();
		i23();
		i10();
		i27();
		i29();
		i28();
		i18();
		i30();
		i5();
		i20();
		i24();
		i23();
		i8();
		i14();
		i20();
		i25();
		i21();
	}
	level--;
	return 0;
}

int i21() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi21\033[0m.\n");
	if (!called) {
		i11();
		i9();
		i26();
		i8();
		i2();
		i14();
		i14();
		i2();
		i0();
		i17();
		i10();
		i25();
		i5();
		i18();
		i17();
		i28();
		i15();
		i26();
		i9();
		i5();
		i14();
		i21();
		i21();
		i11();
		i9();
		i10();
	}
	level--;
	return 0;
}

int i22() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi22\033[0m.\n");
	if (!called) {
		i17();
		i18();
		i30();
		i30();
		i19();
		i22();
		i13();
		i21();
		i3();
		i8();
		i12();
		i16();
		i16();
		i28();
		i30();
	}
	level--;
	return 0;
}

int i23() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi23\033[0m.\n");
	if (!called) {
		i25();
		i11();
		i25();
		i28();
		i24();
		i11();
		i12();
		i2();
		i13();
		i8();
		i22();
		i18();
		i21();
		i12();
		i14();
		i28();
		i28();
		i2();
		i6();
		i23();
		i30();
	}
	level--;
	return 0;
}

int i24() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi24\033[0m.\n");
	if (!called) {
		i25();
		i26();
		i5();
		i3();
		i7();
		i6();
		i3();
		i9();
		i22();
		i3();
		i19();
		i16();
		i30();
		i15();
		i1();
		i17();
		i19();
		i19();
		i29();
		i3();
		i29();
		i28();
		i13();
	}
	level--;
	return 0;
}

int i25() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi25\033[0m.\n");
	if (!called) {
		i23();
		i5();
		i1();
		i2();
		i29();
		i25();
		i30();
		i28();
		i19();
		i26();
		i15();
		i27();
		i26();
		i10();
		i29();
		i24();
		i29();
	}
	level--;
	return 0;
}

int i26() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi26\033[0m.\n");
	if (!called) {
		i8();
		i0();
		i4();
		i3();
		i29();
		i29();
		i26();
		i13();
		i18();
		i1();
		i7();
		i26();
		i10();
		i0();
		i20();
		i29();
		i4();
	}
	level--;
	return 0;
}

int i27() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi27\033[0m.\n");
	if (!called) {
		i12();
		i5();
		i12();
		i23();
		i18();
		i10();
		i13();
		i0();
		i22();
		i25();
		i4();
		i11();
		i30();
		i21();
		i0();
		i23();
		i6();
		i30();
		i17();
		i12();
		i22();
	}
	level--;
	return 0;
}

int i28() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi28\033[0m.\n");
	if (!called) {
		i24();
		i8();
		i28();
		i20();
		i4();
		i0();
		i25();
		i16();
		i6();
		i17();
		i19();
		i21();
		i14();
		i4();
		i22();
		i30();
		i23();
		i23();
		i19();
	}
	level--;
	return 0;
}

int i29() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi29\033[0m.\n");
	if (!called) {
		i26();
		i21();
		i24();
		i13();
		i3();
		i10();
		i10();
		i1();
		i10();
		i29();
		i17();
		i8();
		i17();
		i9();
		i9();
		i2();
		i12();
		i24();
		i26();
		i6();
		i9();
		i16();
		i9();
		i10();
		i0();
		i0();
		i6();
	}
	level--;
	return 0;
}

int i30() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi30\033[0m.\n");
	if (!called) {
		i6();
		i23();
		i12();
		i14();
		i25();
		i10();
		i18();
		i28();
		i18();
		i22();
		i1();
		i6();
		i24();
		i16();
		i20();
		i19();
		i6();
		i16();
	}
	level--;
	return 0;
}

int main() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mmain\033[0m.\n");
	if (!called) {
		i8();
		i27();
		i17();
		i24();
		i27();
		i10();
		i7();
		i6();
		i21();
		i8();
		i30();
		i29();
		i10();
		i11();
		i18();
	}
	level--;
	return 0;
}

