//This program generated by a Python script.
#include <stdio.h>
#define lprintf for(int i = 0; i < level; i++) printf("  "); printf

int level = 0;


int i0();
int i1();
int i2();
int i3();
int i4();
int i5();
int i6();
int i7();
int i8();
int i9();
int i10();
int i11();
int i12();
int i13();
int i14();
int i15();
int i16();
int i17();
int i18();
int i19();

int i0() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi0\033[0m.\n");
	if (!called) {
		i2();
		i6();
		i7();
		i15();
	}
	level--;
	return 0;
}

int i1() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi1\033[0m.\n");
	if (!called) {
		i12();
		i7();
		i13();
		i14();
	}
	level--;
	return 0;
}

int i2() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi2\033[0m.\n");
	if (!called) {
		i7();
		i14();
	}
	level--;
	return 0;
}

int i3() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi3\033[0m.\n");
	if (!called) {
		i7();
	}
	level--;
	return 0;
}

int i4() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi4\033[0m.\n");
	if (!called) {
		i5();
		i0();
		i5();
		i11();
	}
	level--;
	return 0;
}

int i5() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi5\033[0m.\n");
	if (!called) {
		i14();
		i3();
		i10();
		i15();
	}
	level--;
	return 0;
}

int i6() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi6\033[0m.\n");
	if (!called) {
		i17();
		i8();
	}
	level--;
	return 0;
}

int i7() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi7\033[0m.\n");
	if (!called) {
		i5();
		i0();
		i18();
	}
	level--;
	return 0;
}

int i8() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi8\033[0m.\n");
	if (!called) {
		i17();
		i15();
		i7();
	}
	level--;
	return 0;
}

int i9() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi9\033[0m.\n");
	if (!called) {
		i6();
		i4();
		i2();
	}
	level--;
	return 0;
}

int i10() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi10\033[0m.\n");
	if (!called) {
		i11();
		i1();
	}
	level--;
	return 0;
}

int i11() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi11\033[0m.\n");
	if (!called) {
		i18();
		i4();
	}
	level--;
	return 0;
}

int i12() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi12\033[0m.\n");
	if (!called) {
		i12();
		i4();
		i1();
		i9();
	}
	level--;
	return 0;
}

int i13() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi13\033[0m.\n");
	if (!called) {
		i7();
	}
	level--;
	return 0;
}

int i14() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi14\033[0m.\n");
	if (!called) {
		i14();
		i5();
	}
	level--;
	return 0;
}

int i15() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi15\033[0m.\n");
	if (!called) {
		i19();
	}
	level--;
	return 0;
}

int i16() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi16\033[0m.\n");
	if (!called) {
		i15();
	}
	level--;
	return 0;
}

int i17() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi17\033[0m.\n");
	if (!called) {
		i9();
	}
	level--;
	return 0;
}

int i18() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi18\033[0m.\n");
	if (!called) {
		i0();
	}
	level--;
	return 0;
}

int i19() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mi19\033[0m.\n");
	if (!called) {
		i1();
	}
	level--;
	return 0;
}

int main() {
	static int called = -1;
	called++;
	level++;
	lprintf("Called \033[32mmain\033[0m.\n");
	if (!called) {
		i13();
		i7();
		i8();
	}
	level--;
	return 0;
}

