# ALL Modes
# 1st bit - QED
# 2nd bit - CFTSS
# 3rd bit - CFCSS
# 4th bit - GlobalCFCSS

SOURCES      = hello.c
QED_MODE     = 4
NUM_CFTSS_BB = 10
APPLICATION  = hello
OPTIMIZATION = 
BENCHLANG    = C

# Include standard template for this suite
-include ../Makefile.defaults

nomakefiles:
	@echo "*** Oops!  I didn't find a Makefile.defaults file. "
	@echo
